#!/bin/bash
# Complete Test Plan for Security Features
# Run each test step by step

echo "🧪 Security Features Testing Plan"
echo "=================================="
echo ""

echo "📋 Test 1: Force Fresh OAuth to Trigger New Code"
echo "------------------------------------------------"
echo "1. In mobile app, LOGOUT completely"
echo "2. Clear app data (or reinstall app)"
echo "3. Login with a DIFFERENT Google account (not searchrks@gmail.com)"
echo "   OR"
echo "4. Revoke app access at https://myaccount.google.com/permissions"
echo "   Then login again with same account"
echo ""
echo "Expected Results:"
echo "  ✅ New encrypted token (doesn't start with ya29.)"
echo "  ✅ Token expiration timestamps populated"
echo "  ✅ Security audit log entries created"
echo ""

echo "🔍 Verification Query:"
echo "psql postgresql://rishisamadhiya@localhost:5432/cvapplyr_dev -c \\"
echo "  \"SELECT id, email, "
echo "   CASE WHEN google_access_token LIKE 'ya29.%' THEN '❌ UNENCRYPTED' ELSE '✅ ENCRYPTED' END as status,"
echo "   google_token_expires_at"
echo "   FROM users ORDER BY id DESC LIMIT 1;\""
echo ""
echo "---"
echo ""

echo "📋 Test 2: Verify Security Audit Logging"
echo "----------------------------------------"
echo "After fresh OAuth login above, run:"
echo ""
echo "psql postgresql://rishisamadhiya@localhost:5432/cvapplyr_dev -c \\"
echo "  \"SELECT event_type, event_category, details->>'provider', success, created_at"
echo "   FROM security_audit_log ORDER BY created_at DESC LIMIT 10;\""
echo ""
echo "Expected Results:"
echo "  ✅ OAUTH_TOKEN_GRANTED event"
echo "  ✅ USER_REGISTERED event (if new user)"
echo "  ✅ Provider set to 'google'"
echo "  ✅ IP address captured"
echo ""
echo "---"
echo ""

echo "📋 Test 3: Test Token Auto-Refresh"
echo "-----------------------------------"
echo "OPTION A: Quick Test (Force Expiration)"
echo ""
echo "# Get the latest user ID"
echo "USER_ID=\$(psql postgresql://rishisamadhiya@localhost:5432/cvapplyr_dev -tAc \"SELECT id FROM users ORDER BY id DESC LIMIT 1\")"
echo ""
echo "# Force token to be expired"
echo "psql postgresql://rishisamadhiya@localhost:5432/cvapplyr_dev -c \\"
echo "  \"UPDATE users SET google_token_expires_at = NOW() - INTERVAL '1 hour' WHERE id = \${USER_ID};\""
echo ""
echo "# Now send an email via the app"
echo "# Check server logs for:"
echo "#   ⏰ Token expired, refreshing..."
echo "#   🔄 Refreshing Google OAuth token for user X"
echo "#   ✅ Token refreshed successfully"
echo ""
echo "# Verify new expiration:"
echo "psql postgresql://rishisamadhiya@localhost:5432/cvapplyr_dev -c \\"
echo "  \"SELECT id, email, google_token_expires_at FROM users WHERE id = \${USER_ID};\""
echo ""
echo "Expected Results:"
echo "  ✅ Server logs show token refresh"
echo "  ✅ New expiration time in database (~1 hour from now)"
echo "  ✅ Email sent successfully"
echo "  ✅ Audit log shows token refresh event"
echo ""
echo "---"
echo ""

echo "📋 Test 4: Test Login/Logout Audit Logging"
echo "------------------------------------------"
echo "In the mobile app or web:"
echo "1. Logout"
echo "2. Login with email/password (if you have local account)"
echo "3. Try logging in with WRONG password"
echo ""
echo "# Check audit logs:"
echo "psql postgresql://rishisamadhiya@localhost:5432/cvapplyr_dev -c \\"
echo "  \"SELECT event_type, success, details, error_message, created_at"
echo "   FROM security_audit_log WHERE event_category = 'auth' ORDER BY created_at DESC;\""
echo ""
echo "Expected Results:"
echo "  ✅ LOGIN_SUCCESS events"
echo "  ✅ LOGIN_FAILED events (with reason in details)"
echo "  ✅ IP addresses logged"
echo ""
echo "---"
echo ""

echo "📊 COMPREHENSIVE VERIFICATION"
echo "============================"
echo "Run this query after all tests:"
echo ""
echo "psql postgresql://rishisamadhiya@localhost:5432/cvapplyr_dev -c \\"
echo "  \"SELECT "
echo "   (SELECT COUNT(*) FROM security_audit_log) as total_audit_logs,"
echo "   (SELECT COUNT(*) FROM users WHERE google_token_expires_at IS NOT NULL) as users_with_expiration,"
echo "   (SELECT COUNT(*) FROM users WHERE google_access_token NOT LIKE 'ya29.%' AND google_access_token IS NOT NULL) as users_with_encrypted_tokens;\""
echo ""
echo "✅ All 4 features working if:"
echo "  - total_audit_logs > 0"
echo "  - users_with_expiration > 0"  
echo "  - users_with_encrypted_tokens > 0"
echo ""
