// AUTO-GENERATED from an audited synonym workflow (job-search interchangeable terms; false-synonyms &
// ambiguous abbreviations removed: rn/pm/tf/es/…). Mirror kept in server/utils/searchSynonyms.js AND
// MobileApp/utils/searchSynonyms.ts — regenerate/edit both together.
'use strict';
const SYNONYM_GROUPS = [
  [".net","dotnet","dot net"],
  ["c#","csharp","c sharp","c-sharp"],
  ["c++","cpp","cplusplus"],
  ["javascript","js"],
  ["typescript","ts"],
  ["python","py"],
  ["golang","go","go lang"],
  ["objective-c","objc","objective c"],
  ["kotlin","kt"],
  ["f#","fsharp","f sharp","f-sharp"],
  ["visual basic","vb"],
  ["node.js","nodejs","node"],
  ["react","reactjs","react.js"],
  ["react native","reactjs native"],
  ["vue","vuejs","vue.js"],
  ["next.js","nextjs","next js"],
  ["svelte","sveltejs","svelte.js"],
  ["flutter","flutter sdk"],
  ["jetpack compose","android compose"],
  ["swiftui","swift ui"],
  ["asp.net core",".net core","aspnet core"],
  ["spring boot","springboot"],
  ["ruby on rails","rails","ror"],
  ["express.js","express","expressjs"],
  ["nestjs","nest.js"],
  ["kubernetes","k8s","kube"],
  ["aws","amazon web services"],
  ["gcp","google cloud","google cloud platform"],
  ["azure","microsoft azure"],
  ["ci/cd","cicd","ci cd","continuous integration/continuous delivery","continuous integration and continuous delivery","continuous integration/continuous deployment"],
  ["docker","dockerized","dockerised"],
  ["devops","dev ops","dev-ops"],
  ["sre","site reliability engineering","site reliability engineer"],
  ["iac","infrastructure as code","infrastructure-as-code"],
  ["ci","continuous integration"],
  ["cd","continuous delivery","continuous deployment"],
  ["gke","google kubernetes engine"],
  ["eks","elastic kubernetes service","amazon eks"],
  ["aks","azure kubernetes service"],
  ["gitops","git ops","git-ops"],
  ["helm","helm charts"],
  ["ansible","ansible playbooks"],
  ["k3s","k3s kubernetes"],
  ["machine learning","ml","machine-learning"],
  ["artificial intelligence","ai"],
  ["deep learning","dl","deep-learning"],
  ["natural language processing","nlp"],
  ["data science","ds","data scientist","data-scientist"],
  ["generative ai","gen ai","genai","gen-ai","generative artificial intelligence"],
  ["large language model","llm","large language models","llms","large-language-model"],
  ["power bi","powerbi","power-bi","microsoft power bi"],
  ["etl","extract transform load","extract-transform-load","extract, transform, load"],
  ["data warehouse","dwh","data warehousing","datawarehouse","data-warehouse"],
  ["computer vision","computer-vision"],
  ["machine learning engineer","ml engineer","ml-engineer"],
  ["mlops","ml ops","ml-ops","machine learning operations"],
  ["neural network","neural net","neural networks","neural nets","nn"],
  ["reinforcement learning","reinforcement-learning"],
  ["business intelligence","business-intelligence"],
  ["big data","big-data","bigdata"],
  ["data engineer","data-engineer","data engineering"],
  ["data analyst","data-analyst","data analytics","analytics analyst"],
  ["postgresql","postgres","postgre","psql"],
  ["mysql","my sql"],
  ["sql server","mssql","ms sql","microsoft sql server","ms sql server"],
  ["mongodb","mongo","mongo db"],
  ["elasticsearch","elastic search","elastic"],
  ["oracle database","oracle db","oracle"],
  ["dynamodb","dynamo db","dynamo","amazon dynamodb","aws dynamodb"],
  ["qa","quality assurance","q/a"],
  ["qa engineer","quality assurance engineer","qa tester","quality engineer"],
  ["sdet","software development engineer in test","software design engineer in test"],
  ["test automation","automation testing","automated testing","test automation engineer","automation test engineer","qa automation engineer"],
  ["manual testing","manual tester","manual qa"],
  ["software tester","software test engineer","test engineer"],
  ["selenium","selenium webdriver"],
  ["appium","appium automation"],
  ["cyber security","cybersecurity","cyber-security"],
  ["information security","infosec"],
  ["penetration testing","pen testing","pentest","pen test","penetration tester","pentester","ethical hacker","ethical hacking"],
  ["soc analyst","security operations center analyst","security operations analyst"],
  ["application security","appsec","application security engineer"],
  ["vulnerability assessment","vulnerability testing"],
  ["security analyst","it security analyst","information security analyst","cybersecurity analyst"],
  ["performance testing","load testing","performance test engineer"],
  ["api testing","api test automation"],
  ["security engineer","cyber security engineer","cybersecurity engineer"],
  ["software engineer","software developer","swe","sde","software development engineer","software engineer (sw)"],
  ["full stack developer","fullstack developer","full-stack developer","full stack engineer","fullstack engineer","full-stack engineer"],
  ["backend developer","back-end developer","backend engineer","back-end engineer","back end developer","back end engineer"],
  ["frontend developer","front-end developer","frontend engineer","front-end engineer","front end developer","front end engineer"],
  ["devops engineer","dev ops engineer","dev-ops engineer"],
  ["tech lead","technical lead","tl","technical team lead"],
  ["engineering manager","em","software engineering manager","manager, engineering"],
  ["solution architect","solutions architect"],
  ["product manager","product management"],
  ["project manager","project management"],
  ["program manager","program management"],
  ["business analyst","ba"],
  ["product owner","po"],
  ["scrum master","scrummaster"],
  ["project management professional","pmp"],
  ["ui designer","ui","user interface designer"],
  ["ux designer","ux","user experience designer"],
  ["ui/ux designer","ui/ux","ui ux designer","ui-ux designer","ux/ui designer","ui and ux designer"],
  ["product designer","product design"],
  ["hr","human resources","human resource"],
  ["digital marketer","digital marketing","digital marketing specialist"],
  ["sales","salesperson","sales representative","sales rep"],
  ["business development","biz dev","bd","business development representative","bdr"],
  ["accountant","accounts","accounting"],
  ["graphic designer","graphic design"],
  ["fintech","financial technology","fin tech","fin-tech"],
  ["healthtech","healthcare technology","health tech","health-tech","health technology"],
  ["edtech","education technology","ed tech","ed-tech","educational technology"],
  ["e-commerce","ecommerce","e commerce","electronic commerce"],
  ["senior","sr","snr","sr."],
  ["junior","jr","jnr","jr."],
  ["entry level","entry-level","fresher","graduate","grad","new grad","recent graduate","entry level position"],
  ["intern","internship","interns","internships"],
  ["remote","work from home","wfh","work-from-home","remote work","telecommute","telework"]
];
const LOOKUP = new Map();
for (const g of SYNONYM_GROUPS) for (const t of g) if (!LOOKUP.has(t)) LOOKUP.set(t, g);
// Full synonym set for a term (itself + interchangeable variants).
function expandTerm(term) { const t = String(term || '').toLowerCase().trim(); if (!t) return []; return LOOKUP.has(t) ? LOOKUP.get(t).slice() : [t]; }
// SQL-safe variants: matching is substring LIKE, so do NOT introduce NEW short tokens (<3 chars, no symbol)
// that would match inside unrelated words. Keep the original token + only length>=3 / symbol-bearing synonyms.
function expandForSql(token) { const t = String(token || '').toLowerCase().trim(); if (!t) return []; const out = [t]; for (const v of expandTerm(t)) if (v !== t && (v.length >= 3 || /[.#+]/.test(v)) && !out.includes(v)) out.push(v); return out; }
module.exports = { SYNONYM_GROUPS, expandTerm, expandForSql };
