// AUTO-GENERATED — ALL-FIELDS job-search synonym map (deterministic union-find merge of the audited
// all-fields workflow + the original IT seed, so nothing regresses). False-synonyms & cross-field ambiguous
// abbreviations removed (pa/ta/md/pt/ot/ea/ae/ra/ee/pr/vet/pm/tf/es…); rn=registered nurse. Mirror kept in
// server/utils/searchSynonyms.js AND MobileApp/utils/searchSynonyms.ts — regenerate both together.
'use strict';
const SYNONYM_GROUPS = [
  [".net","dotnet","dot net"],
  ["c#","csharp","c sharp","c-sharp"],
  ["c++","cpp","cplusplus"],
  ["javascript","js"],
  ["typescript","ts"],
  ["python","py"],
  ["golang","go","go lang"],
  ["objective-c","objc","objective c"],
  ["kotlin","kt"],
  ["f#","fsharp","f sharp","f-sharp"],
  ["visual basic","vb"],
  ["node.js","nodejs","node"],
  ["react","reactjs","react.js"],
  ["react native","reactjs native"],
  ["vue","vuejs","vue.js"],
  ["next.js","nextjs","next js"],
  ["svelte","sveltejs","svelte.js"],
  ["flutter","flutter sdk"],
  ["jetpack compose","android compose"],
  ["swiftui","swift ui"],
  ["asp.net core",".net core","aspnet core"],
  ["spring boot","springboot"],
  ["ruby on rails","rails","ror"],
  ["express.js","express","expressjs"],
  ["nestjs","nest.js"],
  ["kubernetes","k8s","kube"],
  ["aws","amazon web services"],
  ["gcp","google cloud","google cloud platform"],
  ["azure","microsoft azure"],
  ["ci/cd","cicd","ci cd","continuous integration/continuous delivery","continuous integration and continuous delivery","continuous integration/continuous deployment"],
  ["docker","dockerized","dockerised"],
  ["devops","dev ops","dev-ops"],
  ["sre","site reliability engineering","site reliability engineer"],
  ["iac","infrastructure as code","infrastructure-as-code"],
  ["ci","continuous integration"],
  ["cd","continuous delivery","continuous deployment"],
  ["gke","google kubernetes engine"],
  ["eks","elastic kubernetes service","amazon eks"],
  ["aks","azure kubernetes service"],
  ["gitops","git ops","git-ops"],
  ["helm","helm charts"],
  ["ansible","ansible playbooks"],
  ["k3s","k3s kubernetes"],
  ["machine learning","ml","machine-learning"],
  ["artificial intelligence","ai"],
  ["deep learning","dl","deep-learning"],
  ["natural language processing","nlp"],
  ["data science","ds","data scientist","data-scientist"],
  ["generative ai","gen ai","genai","gen-ai","generative artificial intelligence"],
  ["large language model","llm","large language models","llms","large-language-model"],
  ["power bi","powerbi","power-bi","microsoft power bi"],
  ["etl","extract transform load","extract-transform-load","extract, transform, load"],
  ["data warehouse","dwh","data warehousing","datawarehouse","data-warehouse"],
  ["computer vision","computer-vision"],
  ["machine learning engineer","ml engineer","ml-engineer"],
  ["mlops","ml ops","ml-ops","machine learning operations"],
  ["neural network","neural net","neural networks","neural nets"],
  ["reinforcement learning","reinforcement-learning"],
  ["business intelligence","business-intelligence"],
  ["big data","big-data","bigdata"],
  ["data engineer","data-engineer","data engineering"],
  ["data analyst","data-analyst","data analytics","analytics analyst"],
  ["postgresql","postgres","postgre","psql"],
  ["mysql","my sql"],
  ["sql server","mssql","ms sql","microsoft sql server","ms sql server"],
  ["mongodb","mongo","mongo db"],
  ["elasticsearch","elastic search","elastic"],
  ["oracle database","oracle db","oracle"],
  ["dynamodb","dynamo db","dynamo","amazon dynamodb","aws dynamodb"],
  ["qa","quality assurance","q/a"],
  ["qa engineer","quality assurance engineer","qa tester","quality engineer"],
  ["sdet","software development engineer in test","software design engineer in test"],
  ["test automation","automation testing","automated testing","test automation engineer","automation test engineer","qa automation engineer"],
  ["manual testing","manual tester","manual qa"],
  ["software tester","software test engineer","test engineer"],
  ["selenium","selenium webdriver"],
  ["appium","appium automation"],
  ["cyber security","cybersecurity","cyber-security"],
  ["information security","infosec"],
  ["penetration testing","pen testing","pentest","pen test","penetration tester","pentester","ethical hacker","ethical hacking"],
  ["soc analyst","security operations center analyst","security operations analyst"],
  ["application security","appsec","application security engineer"],
  ["vulnerability assessment","vulnerability testing"],
  ["security analyst","it security analyst","information security analyst","cybersecurity analyst"],
  ["performance testing","load testing","performance test engineer"],
  ["api testing","api test automation"],
  ["security engineer","cyber security engineer","cybersecurity engineer"],
  ["software engineer","software developer","swe","sde","software development engineer","software engineer (sw)"],
  ["full stack developer","fullstack developer","full-stack developer","full stack engineer","fullstack engineer","full-stack engineer"],
  ["backend developer","back-end developer","backend engineer","back-end engineer","back end developer","back end engineer"],
  ["frontend developer","front-end developer","frontend engineer","front-end engineer","front end developer","front end engineer"],
  ["devops engineer","dev ops engineer","dev-ops engineer"],
  ["tech lead","technical lead","tl","technical team lead"],
  ["engineering manager","em","software engineering manager","manager, engineering"],
  ["solution architect","solutions architect"],
  ["product manager","product management"],
  ["project manager","project management"],
  ["program manager","program management","programme manager"],
  ["business analyst","ba"],
  ["product owner","po"],
  ["scrum master","scrummaster"],
  ["project management professional","pmp"],
  ["ui designer","ui","user interface designer","ui design"],
  ["ux designer","ux","user experience designer","ux design"],
  ["ui/ux designer","ui/ux","ui ux designer","ui-ux designer","ux/ui designer","ui and ux designer"],
  ["product designer","product design"],
  ["hr","human resources","human resource","h.r."],
  ["digital marketer","digital marketing","digital marketing specialist","online marketing","internet marketing"],
  ["sales","salesperson","sales representative","sales rep","sales person","salesman","saleswoman","sales agent"],
  ["business development","biz dev","bd","business development representative","bdr","business development rep","business development manager","bdm"],
  ["accountant","accounts","accounting","accounting professional"],
  ["graphic designer","graphic design","graphics designer","graphic artist"],
  ["fintech","financial technology","fin tech","fin-tech"],
  ["healthtech","healthcare technology","health tech","health-tech","health technology"],
  ["edtech","education technology","ed tech","ed-tech","educational technology"],
  ["e-commerce","ecommerce","e commerce","electronic commerce"],
  ["senior","sr","snr","sr."],
  ["junior","jr","jnr","jr."],
  ["entry level","entry-level","fresher","graduate","grad","new grad","recent graduate","entry level position","entlevel","freshers"],
  ["intern","internship","interns","internships","trainee","traineeship"],
  ["remote","work from home","wfh","work-from-home","remote work","telecommute","telework","remotely"],
  ["registered nurse","rn","r.n."],
  ["nurse practitioner","advanced practice registered nurse","aprn"],
  ["licensed practical nurse","lpn","licensed vocational nurse","lvn"],
  ["certified nursing assistant","cna","certified nurse assistant","nursing assistant","nurse aide","nursing aide"],
  ["physician","doctor","medical doctor"],
  ["general practitioner","gp","family physician","family doctor","family practitioner"],
  ["physician assistant","physician associate","pa-c"],
  ["emergency medical technician","emt"],
  ["paramedic","emt-paramedic"],
  ["radiographer","radiologic technologist","radiology technologist","radiological technologist","x-ray technician","x-ray technologist","rad tech"],
  ["phlebotomist","phlebotomy technician"],
  ["respiratory therapist","registered respiratory therapist","rrt"],
  ["anesthesiologist","anaesthesiologist","anaesthetist","anesthetist"],
  ["midwife","certified nurse midwife","nurse midwife"],
  ["medical assistant","clinical medical assistant"],
  ["surgeon","surgical doctor"],
  ["staff nurse","ward nurse"],
  ["physical therapist","physiotherapist","physio","physical therapy","physiotherapy"],
  ["occupational therapist","occupational therapy"],
  ["speech language pathologist","speech-language pathologist","speech and language pathologist","speech pathologist","speech therapist","speech language therapist","speech and language therapist","slp","speech therapy"],
  ["dietitian","dietician","nutritionist","registered dietitian"],
  ["pharmacist","registered pharmacist","licensed pharmacist"],
  ["pharmacy technician","pharmacy tech","pharm tech"],
  ["optometrist","doctor of optometry"],
  ["counselor","counsellor"],
  ["clinical social worker","licensed clinical social worker","lcsw"],
  ["audiologist","doctor of audiology"],
  ["medical coder","medical coding specialist","clinical coder","diagnostic coder","medical coding technician","certified coder"],
  ["medical biller","medical billing specialist","medical billing clerk","insurance biller","medical billing associate"],
  ["medical coder and biller","medical biller and coder","medical coding and billing specialist","medical billing and coding specialist"],
  ["medical transcriptionist","medical transcriber","medical transcription specialist","healthcare documentation specialist"],
  ["healthcare administrator","health care administrator","healthcare admin","medical administrator","health services administrator","healthcare administration"],
  ["clinical research associate","cra","clinical research monitor","clinical trial monitor"],
  ["dentist","dental surgeon","doctor of dental surgery","dds","dmd","doctor of dental medicine"],
  ["dental hygienist","registered dental hygienist","rdh","oral hygienist"],
  ["dental assistant","dental care assistant","registered dental assistant","certified dental assistant"],
  ["orthodontist","orthodontic specialist","braces specialist"],
  ["veterinarian","veterinary surgeon","veterinary doctor","doctor of veterinary medicine","dvm","animal doctor"],
  ["veterinary technician","vet tech","veterinary technologist","animal health technician","veterinary nurse"],
  ["chartered accountant","ca"],
  ["certified public accountant","cpa"],
  ["bookkeeper","book keeper","book-keeper","bookkeeping clerk"],
  ["accounts payable","ap clerk","accounts payable clerk","accounts payable specialist"],
  ["accounts receivable","ar clerk","accounts receivable clerk","accounts receivable specialist"],
  ["auditor","audit associate","audit professional"],
  ["internal auditor","internal audit specialist"],
  ["tax accountant","tax preparer","tax specialist"],
  ["cost accountant","costing accountant","cost accounting analyst"],
  ["payroll specialist","payroll administrator","payroll clerk","payroll officer"],
  ["financial controller","controller","finance controller"],
  ["staff accountant","general ledger accountant","gl accountant"],
  ["financial analyst","finance analyst"],
  ["investment banker","investment banking"],
  ["chartered financial analyst","cfa","cfa charterholder"],
  ["financial advisor","financial adviser","financial planner","personal financial advisor","financial consultant"],
  ["wealth manager","wealth management","wealth advisor","wealth adviser"],
  ["loan officer","loan originator"],
  ["bank teller","teller"],
  ["underwriter","underwriting"],
  ["risk analyst","risk management analyst"],
  ["lawyer","attorney","attorney at law","attorney-at-law"],
  ["paralegal","legal assistant"],
  ["litigation attorney","litigation lawyer","litigator"],
  ["general counsel","chief legal officer","head of legal","clo"],
  ["in-house counsel","corporate counsel"],
  ["legal counsel","legal advisor","legal adviser"],
  ["notary public","notary"],
  ["contract manager","contracts manager"],
  ["account executive","account exec"],
  ["sales development representative","sdr","sales development rep"],
  ["key account manager","kam","key accounts manager"],
  ["sales manager","sales team manager"],
  ["inside sales","inside sales representative","inside sales rep"],
  ["field sales","field sales representative","field sales rep","outside sales","outside sales representative","outside sales rep"],
  ["territory manager","territory sales manager","area sales manager"],
  ["presales","pre-sales","pre sales","presales consultant","pre-sales consultant"],
  ["sales director","director of sales","head of sales"],
  ["vp of sales","vp sales","vice president of sales","vice president sales"],
  ["regional sales manager","regional sales director"],
  ["national sales manager","national sales director"],
  ["sales engineer","sales engineering"],
  ["sales consultant","sales advisor","sales adviser"],
  ["retail sales associate","retail sales assistant","retail associate","sales assistant","sales associate","retail assistant","shop assistant","store associate"],
  ["telesales","tele sales","telesales representative","telesales rep","telemarketer","telemarketing representative"],
  ["sales coordinator","sales support coordinator"],
  ["chief sales officer","cso"],
  ["sales operations","sales ops","sales operations manager","sales ops manager"],
  ["enterprise account executive","enterprise sales executive"],
  ["channel sales manager","channel manager","channel account manager"],
  ["customer success manager","csm","customer success mgr"],
  ["marketing manager","mktg manager","marketing mgr"],
  ["seo specialist","seo","search engine optimization","search engine optimization specialist"],
  ["search engine marketing","sem","paid search"],
  ["ppc","pay per click","pay-per-click","ppc specialist","pay per click specialist"],
  ["copywriter","content writer","copy writer"],
  ["social media manager","social media marketing manager"],
  ["brand manager","brand marketing manager","branding manager"],
  ["growth marketer","growth marketing","growth hacker"],
  ["public relations","public relations specialist","pr specialist"],
  ["communications manager","communication manager","comms manager"],
  ["marketing executive","marketing exec"],
  ["performance marketing","performance marketer"],
  ["chief marketing officer","cmo"],
  ["hr generalist","human resources generalist"],
  ["recruiter","recruitment consultant","recruiting specialist","recruitment specialist"],
  ["technical recruiter","tech recruiter","it recruiter"],
  ["talent acquisition specialist","talent acquisition partner","ta specialist","talent acquisition consultant"],
  ["hr business partner","human resources business partner","hrbp","people business partner"],
  ["people operations","people ops","people & operations"],
  ["compensation and benefits","comp and benefits","comp & benefits","compensation & benefits","c&b"],
  ["hr manager","human resources manager","manager, human resources","manager of human resources"],
  ["learning and development","learning & development","l&d","training and development","training & development","learning and development specialist","l&d specialist","learning & development specialist"],
  ["hr executive","human resources executive"],
  ["hr coordinator","human resources coordinator"],
  ["hr assistant","human resources assistant"],
  ["hr administrator","human resources administrator","hr admin"],
  ["hr director","human resources director","director of human resources","director, human resources"],
  ["hr specialist","human resources specialist"],
  ["talent acquisition manager","recruiting manager","recruitment manager","talent acquisition lead"],
  ["recruiting coordinator","recruitment coordinator","talent acquisition coordinator"],
  ["chro","chief human resources officer","chief people officer","chief hr officer"],
  ["hr consultant","human resources consultant"],
  ["hris analyst","hr systems analyst","human resources information system analyst","hris specialist"],
  ["headhunter","executive recruiter","executive search consultant"],
  ["sourcer","talent sourcer","sourcing specialist","recruiting sourcer"],
  ["hr officer","human resources officer"],
  ["hr analyst","human resources analyst"],
  ["employee relations specialist","employee relations partner","er specialist"],
  ["hr partner","human resources partner"],
  ["vp of human resources","vp of hr","vice president of human resources","vice president human resources","vp people"],
  ["organizational development specialist","org development specialist","od specialist","organisational development specialist"],
  ["hr vice president","head of hr","head of human resources","head of people"],
  ["hr intern","human resources intern"],
  ["mechanical engineer","mechanical engineering","mech engineer"],
  ["electrical engineer","electrical engineering","elec engineer"],
  ["civil engineer","civil engineering"],
  ["chemical engineer","chemical engineering","chem engineer"],
  ["industrial engineer","industrial engineering"],
  ["mechatronics engineer","mechatronic engineer","mechatronics engineering"],
  ["aerospace engineer","aerospace engineering","aeronautical engineer","aeronautical engineering"],
  ["structural engineer","structural engineering"],
  ["biomedical engineer","biomedical engineering","bio-medical engineer"],
  ["environmental engineer","environmental engineering","environmental engineering specialist"],
  ["petroleum engineer","petroleum engineering","oil and gas engineer"],
  ["marine engineer","marine engineering"],
  ["instrumentation engineer","instrumentation engineering","instrumentation and control engineer","instrument engineer","i&c engineer"],
  ["cad designer","draughtsman","draftsman","drafter","draughtsperson","draftsperson","cad draughtsman","cad drafter","cad technician","cad operator"],
  ["production manager","manufacturing manager"],
  ["quality control inspector","qc inspector","quality inspector"],
  ["cnc machinist","c.n.c. machinist","computer numerical control machinist"],
  ["machine operator","machine operative"],
  ["maintenance technician","maintenance tech","industrial maintenance technician","maintenance mechanic"],
  ["plant manager","factory manager","works manager"],
  ["process engineer","manufacturing process engineer"],
  ["production supervisor","manufacturing supervisor","production foreman"],
  ["assembler","assembly operator","assembly worker","assembly technician"],
  ["tool and die maker","tool & die maker","toolmaker","tool maker"],
  ["fabricator","metal fabricator","fabrication technician"],
  ["production planner","production scheduler","manufacturing planner"],
  ["supply chain manager","supply-chain manager"],
  ["logistics coordinator","logistics co-ordinator"],
  ["procurement","purchasing"],
  ["procurement manager","purchasing manager"],
  ["procurement specialist","purchasing specialist"],
  ["procurement officer","purchasing officer"],
  ["procurement executive","purchasing executive"],
  ["procurement analyst","purchasing analyst"],
  ["buyer","purchaser","purchasing agent"],
  ["warehouse associate","warehouse worker","warehouse operative","warehouse operator","warehouse assistant"],
  ["warehouse manager","warehousing manager"],
  ["inventory manager","inventory control manager"],
  ["inventory analyst","inventory control analyst"],
  ["inventory clerk","inventory control clerk"],
  ["inventory controller","stock controller"],
  ["materials manager","material manager"],
  ["materials planner","material planner"],
  ["freight forwarder","freight forwarding agent","forwarding agent","freight forwarding executive"],
  ["dispatcher","despatcher"],
  ["demand planner","demand planning analyst"],
  ["supply planner","supply planning analyst"],
  ["storekeeper","store keeper","storeman","stores keeper","storesman"],
  ["import export executive","import/export executive","export import executive","exim executive"],
  ["forklift operator","forklift driver","fork lift operator","lift truck operator","fork truck operator","forklift truck operator"],
  ["picker packer","picker/packer","pick packer"],
  ["material handler","materials handler"],
  ["teacher","educator","school teacher","schoolteacher"],
  ["tutor","private tutor","academic tutor","tuition teacher"],
  ["professor","college professor","university professor"],
  ["lecturer","university lecturer","college lecturer"],
  ["adjunct professor","adjunct faculty","adjunct instructor","adjunct lecturer","adjunct"],
  ["teaching assistant","teacher's aide","teachers aide","teacher aide","classroom assistant"],
  ["paraprofessional","paraeducator","para-educator","instructional aide","instructional assistant"],
  ["principal","school principal","headmaster","headmistress","head teacher","headteacher","head of school"],
  ["assistant principal","vice principal","deputy head","deputy headteacher","deputy head teacher","assistant head teacher"],
  ["instructional designer","learning designer","learning experience designer","instructional design specialist"],
  ["curriculum developer","curriculum designer","curriculum writer","curriculum specialist"],
  ["academic coordinator","academic program coordinator","academic programme coordinator"],
  ["special education teacher","special ed teacher","sped teacher","special needs teacher","special educator","special education instructor"],
  ["preschool teacher","pre-school teacher","pre-k teacher","prek teacher","pre-kindergarten teacher","prekindergarten teacher","nursery teacher"],
  ["substitute teacher","supply teacher","relief teacher","guest teacher"],
  ["corporate trainer","corporate training specialist","training specialist"],
  ["esl teacher","english as a second language teacher","esol teacher","efl teacher","english language teacher"],
  ["school counselor","school counsellor","guidance counselor","guidance counsellor"],
  ["elementary school teacher","elementary teacher","primary school teacher","primary teacher","grade school teacher"],
  ["high school teacher","secondary school teacher","secondary teacher"],
  ["middle school teacher","junior high teacher","junior high school teacher"],
  ["physical education teacher","pe teacher","phys ed teacher","gym teacher"],
  ["kindergarten teacher","kindergarten educator"],
  ["early childhood educator","early years educator","early childhood teacher"],
  ["montessori teacher","montessori guide","montessori educator"],
  ["academic advisor","academic adviser"],
  ["exam invigilator","invigilator","exam proctor","proctor"],
  ["electrician","electrical fitter"],
  ["plumber","plumbing technician"],
  ["welder","welding technician"],
  ["carpenter","joiner","carpenter and joiner"],
  ["hvac technician","hvac tech","hvac mechanic","hvac/r technician","hvacr technician","heating and cooling technician","air conditioning technician","ac technician","a/c technician","air con technician","hvac engineer","heating ventilation and air conditioning technician"],
  ["bricklayer","mason","brick mason","brickmason"],
  ["stonemason","stone mason"],
  ["foreman","forewoman","foreperson","construction foreman"],
  ["site supervisor","construction supervisor","site superintendent","construction superintendent"],
  ["heavy equipment operator","heavy machinery operator","heavy plant operator"],
  ["painter","painter and decorator","painter & decorator"],
  ["roofer","roofing technician","roof installer","roofing installer"],
  ["pipefitter","pipe fitter","steamfitter","steam fitter"],
  ["construction manager","construction project manager"],
  ["quantity surveyor","qs"],
  ["site engineer","construction site engineer"],
  ["scaffolder","scaffold erector","scaffolding erector"],
  ["construction laborer","construction labourer","laborer","labourer","general laborer","general labourer"],
  ["tiler","tile setter","tile installer","tile fitter"],
  ["glazier","glass installer","glass fitter"],
  ["steel fixer","rebar worker","rebar installer","reinforcement fixer"],
  ["drywaller","drywall installer","sheetrock installer"],
  ["concrete finisher","cement finisher","cement mason"],
  ["flooring installer","floor layer","floor fitter","flooring fitter"],
  ["excavator operator","digger operator"],
  ["ironworker","iron worker","steel erector","structural steel erector"],
  ["cost estimator","construction estimator"],
  ["crane operator","crane driver"],
  ["framing carpenter","framer"],
  ["finish carpenter","finishing carpenter","trim carpenter"],
  ["gas engineer","gasfitter","gas fitter"],
  ["handyman","handyperson","handywoman"],
  ["server","waiter","waitress","waiter/waitress","waitstaff","wait staff","waiting staff","food server"],
  ["bartender","bar tender","barman","barmaid","mixologist"],
  ["barback","bar back"],
  ["host","hostess"],
  ["busser","busboy","bus boy","bus person"],
  ["executive chef","exec chef"],
  ["head chef","chef de cuisine"],
  ["sous chef","sous-chef"],
  ["chef de partie","station chef"],
  ["line cook","line chef"],
  ["pastry chef","pastry cook","patissier","pâtissier"],
  ["prep cook","prep chef","preparation cook"],
  ["dishwasher","dish washer","kitchen porter","kitchen steward"],
  ["housekeeper","housekeeping","house keeper","room attendant","chambermaid"],
  ["front desk agent","front desk","front office","front desk clerk","front desk receptionist","guest service agent","guest services agent"],
  ["food and beverage","food & beverage","f&b","f and b"],
  ["bellhop","bellboy","bell boy","bellman","bell attendant"],
  ["cashier","checkout operator","checkout assistant","till operator","checkout clerk","retail cashier"],
  ["store manager","retail store manager","shop manager"],
  ["customer service representative","csr","customer service rep","customer service agent","customer service associate","customer service advisor","customer service specialist","customer care representative","customer care agent","customer care rep","customer care specialist"],
  ["call center agent","call centre agent","contact center agent","contact centre agent","call center representative","call centre representative","contact center representative","call center rep"],
  ["customer support","customer support representative","customer support agent","customer support rep","customer support specialist","customer support associate"],
  ["help desk","helpdesk","service desk"],
  ["merchandiser","retail merchandiser"],
  ["stock associate","stocker","stock clerk","stockroom associate","stock assistant"],
  ["floor supervisor","sales floor supervisor"],
  ["art director","art direction"],
  ["video editor","video editing"],
  ["photographer","photography"],
  ["animator","animation"],
  ["illustrator","illustration"],
  ["motion graphics designer","motion designer","motion graphics artist","motion graphic designer","motion graphics","mograph"],
  ["interior designer","interior design"],
  ["fashion designer","fashion design","apparel designer","clothing designer"],
  ["web designer","website designer","web design"],
  ["content creator","content creation"],
  ["videographer","videography"],
  ["laboratory technician","lab technician","lab tech","laboratory tech"],
  ["laboratory analyst","lab analyst"],
  ["research and development","r&d","r & d","r and d"],
  ["biostatistician","bio-statistician","bio statistician"],
  ["clinical research coordinator","clinical trial coordinator","clinical trials coordinator","clinical study coordinator"],
  ["quality control analyst","qc analyst"],
  ["administrative assistant","admin assistant","administrative aide","administrative support","admin support"],
  ["executive assistant","exec assistant"],
  ["office manager","office management"],
  ["receptionist","front desk executive","front desk officer"],
  ["data entry operator","data entry clerk","data entry executive","data entry associate","data entry specialist"],
  ["personal assistant","personal aide"],
  ["secretary","secretarial"],
  ["office administrator","office admin","office administration"],
  ["front office executive","front office assistant","front office coordinator","front office associate"],
  ["virtual assistant","remote assistant","online assistant"],
  ["back office executive","back office assistant","back office associate","back office coordinator"],
  ["administrative coordinator","admin coordinator"],
  ["administrative officer","admin officer"],
  ["office assistant","office aide"],
  ["clerk","clerical","clerical assistant","office clerk","general clerk"],
  ["typist","keyboard operator"],
  ["office coordinator","office coordination"],
  ["real estate agent","realtor","estate agent","property agent","real estate salesperson","realty agent","real estate sales agent","real-estate agent"],
  ["real estate broker","realty broker","real-estate broker"],
  ["property manager","property management"],
  ["leasing consultant","leasing agent","leasing specialist","leasing professional","leasing associate","leasing representative"],
  ["facilities manager","facility manager","facilities management"],
  ["mortgage broker","mortgage advisor","mortgage adviser","mortgage consultant"],
  ["property consultant","real estate consultant"],
  ["real estate appraiser","property appraiser","property valuer","valuer"],
  ["lettings negotiator","lettings agent","letting agent","lettings consultant"],
  ["property developer","real estate developer"],
  ["community association manager","hoa manager","homeowners association manager"],
  ["buyer's agent","buyers agent","buyer agent"],
  ["seller's agent","sellers agent","listing agent","seller agent"],
  ["pilot","aviator"],
  ["co-pilot","copilot","co pilot","first officer"],
  ["flight attendant","cabin crew","cabin crew member","air hostess","airhostess","stewardess","cabin attendant","air steward","flight steward"],
  ["air traffic controller","atc","air traffic control officer"],
  ["truck driver","lorry driver","hgv driver","lgv driver","trucker"],
  ["delivery driver","courier","courier driver"],
  ["chauffeur","chauffer","private driver","personal driver"],
  ["bus driver","coach driver","psv driver","pcv driver"],
  ["commercial driver","cdl driver"],
  ["ground staff","ground crew","ground handling agent","ground handler"],
  ["taxi driver","cab driver","cabbie","taxi cab driver"],
  ["agronomist","agronomy specialist","crop scientist","crop specialist"],
  ["farm manager","farm operations manager","agricultural manager","farm supervisor"],
  ["environmental scientist","environmental science specialist"],
  ["sustainability manager","sustainability lead","head of sustainability","manager of sustainability"],
  ["renewable energy technician","renewables technician"],
  ["solar technician","solar panel technician","solar pv technician","photovoltaic technician","pv technician"],
  ["wind turbine technician","wind technician","wind turbine service technician","windtech"],
  ["geologist","geological scientist"],
  ["mining engineer","mine engineer"],
  ["forester","forestry manager","forest manager"],
  ["agricultural engineer","ag engineer","agriculture engineer"],
  ["environmental health and safety specialist","ehs specialist","environment health and safety specialist"],
  ["environmental consultant","environmental advisor","environmental adviser"],
  ["horticulturist","horticulturalist"],
  ["arborist","tree surgeon"],
  ["farmhand","farm hand","farm worker","farm labourer","farm laborer","agricultural worker"],
  ["viticulturist","viticulturalist","vineyard manager"],
  ["geotechnical engineer","geotech engineer"],
  ["environmental technician","environmental science technician"],
  ["conservationist","conservation officer","conservation manager"],
  ["hydrologist","hydrology specialist"],
  ["soil scientist","soil specialist","pedologist"],
  ["energy analyst","energy market analyst"],
  ["energy manager","energy management specialist"],
  ["esg analyst","environmental social and governance analyst"],
  ["wildlife biologist","wildlife scientist"],
  ["gis analyst","gis specialist","geographic information systems analyst","geospatial analyst"],
  ["surveyor","land surveyor"],
  ["ecologist","ecological consultant"],
  ["chief executive officer","ceo"],
  ["chief financial officer","cfo"],
  ["chief operating officer","coo"],
  ["chief technology officer","cto"],
  ["chief information officer","cio"],
  ["chief revenue officer","cro"],
  ["chief product officer","cpo"],
  ["chief commercial officer","cco"],
  ["chief data officer","cdo"],
  ["chief information security officer","ciso"],
  ["vice president","vp"],
  ["senior vice president","svp"],
  ["executive vice president","evp"],
  ["general manager","gm"],
  ["director of operations","operations director"],
  ["nonprofit","non-profit","non profit","not-for-profit","not for profit"],
  ["ngo","non-governmental organization","non-governmental organisation","nongovernmental organization","non governmental organization"],
  ["program coordinator","programme coordinator","program co-ordinator","programme co-ordinator"],
  ["program officer","programme officer"],
  ["program director","programme director","director of programs","director of programmes"],
  ["program assistant","programme assistant"],
  ["program associate","programme associate"],
  ["policy analyst","public policy analyst"],
  ["policy advisor","policy adviser"],
  ["grant writer","grants writer","grantwriter"],
  ["grant manager","grants manager"],
  ["social worker","social work"],
  ["community organizer","community organiser"],
  ["civil servant","public servant"],
  ["fundraiser","fund raiser","fund-raiser"],
  ["caseworker","case worker"],
  ["hairstylist","hair stylist","hairdresser","hair dresser"],
  ["makeup artist","make-up artist","make up artist","mua"],
  ["beautician","cosmetologist","cosmetician"],
  ["esthetician","aesthetician","skincare specialist","skin care specialist","skin therapist","facialist"],
  ["massage therapist","masseuse","masseur","massage practitioner","licensed massage therapist","lmt"],
  ["nail technician","nail tech","manicurist","nail artist"],
  ["personal trainer","fitness trainer","personal fitness trainer"],
  ["fitness instructor","gym instructor"],
  ["yoga instructor","yoga teacher"],
  ["lash technician","eyelash technician","lash tech","lash artist"],
  ["hair colorist","hair colourist","hair color specialist","hair colour specialist"],
  ["contract","contractor","contractual","contract to hire","contract-to-hire"],
  ["part time","part-time","parttime"],
  ["full time","full-time","fulltime","ft"],
  ["temporary","temp","temporary contract"],
  ["freelance","freelancer","freelancing"],
  ["hybrid","hybrid remote","partially remote"],
  ["on-site","onsite","on site","in office","in-office","in person","in-person"],
  ["mid level","mid-level","midlevel","intermediate"],
  ["permanent","perm","permanent role","permanent position"],
  ["seasonal","seasonal worker"],
  ["apprentice","apprenticeship"],
  ["gig","gig work","gig worker"],
  ["casual","casual work"],
  ["lead","team lead","team leader"]
];
const LOOKUP = new Map();
for (const g of SYNONYM_GROUPS) for (const t of g) if (!LOOKUP.has(t)) LOOKUP.set(t, g);
function expandTerm(term) { const t = String(term || '').toLowerCase().trim(); if (!t) return []; return LOOKUP.has(t) ? LOOKUP.get(t).slice() : [t]; }
function expandForSql(token) { const t = String(token || '').toLowerCase().trim(); if (!t) return []; const out = [t]; for (const v of expandTerm(t)) if (v !== t && (v.length >= 3 || /[.#+]/.test(v)) && !out.includes(v)) out.push(v); return out; }
module.exports = { SYNONYM_GROUPS, expandTerm, expandForSql };
